name: rick_and_morty_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  equatable: ^2.0.5
  retrofit: ^4.1.0
  talker_flutter: ^4.1.3
  json_annotation: ^4.8.1
  dio: ^5.4.2+1
  talker_dio_logger: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
